# Generated by Django 3.0.2 on 2020-03-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200324_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '🤮🤬😱'), ('2', '💩🤔😰'), ('3', '😑😶🙄'), ('4', '😉🧐🙂'), ('5', '🤩🥳😎')], default='1', max_length=1),
        ),
    ]
