# Generated by Django 3.0.2 on 2020-03-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200325_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('🤮🤬😱', '🤮🤬😱'), ('💩🤔😰', '💩🤔😰'), ('😑😶🙄', '😑😶🙄'), ('😉🧐🙂', '😉🧐🙂'), ('🤩🥳😎', '🤩🥳😎')], default='🤮🤬😱', max_length=3),
        ),
    ]
